---
- name: Test sync-app-apb
  hosts: localhost
  gather_facts: false
  connection: local
  vars_files:
  - /opt/ansible/vars/main.yml
  - /opt/ansible/vars/test.yml

  roles:
  - role: ansible.kubernetes-modules
    install_python_requirements: no
  - role: ansibleplaybookbundle.asb-modules
  
  post_tasks:
  - name: create project for namespace
    openshift_v1_project:
      name: '{{ namespace }}'
  - name: Run the provision role
    include_role: name=provision-sync-app-apb
  - name: Test provision role
    include_role: name=test-sync-app-apb tasks_from=provision.yml
  - name: Run the bind role
    include_role: name=bind-sync-app-apb
  - name: Test bind role
    include_role: name=test-sync-app-apb tasks_from=bind.yml    
  - name: Run the unbind role
    include_role: name=unbind-sync-app-apb
  - name: Test unbind role
    include_role: name=test-sync-app-apb tasks_from=unbind.yml        
  - name: Run the deprovision role
    include_role: name=deprovision-sync-app-apb
  - name: Test deprovision role
    include_role: name=test-sync-app-apb tasks_from=deprovision.yml